### PR TITLE
Use ember-cli project `nodeModulesPath` when available

### PR DESCRIPTION
**Pull request by bantic**
This is a follow-up PR as mentioned in [PR 26](https://github.com/quaertym/ember-cli-dependency-checker/pull/26#issuecomment-90747960).

https://github.com/ember-cli/ember-cli/pull/3771 has added a `nodeModulesPath` property to the ember-cli project. This PR detects and uses that property if it is available, which will allow `ember-cli-dependency-checker` to function properly for ember-cli projects that have a `node_modules` directory outside of the project root.

This also adds a `projectBuilder` test helper to unify the set up of a sample project in tests.

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by mixonic** [comment]
@quaertym I know the powers that be are swinging for an ember-cli release this week. I'd love to see this go with it if you have the time to review.

**Comment by quaertym** [comment]
It looks great, thanks! :beer:

**Comment by mixonic** [comment]
Awwww sweet :-) Are you going to roll a release as well? You are about to make my week.

**Comment by quaertym** [comment]
Yep, it is coming. :+1:

**Comment by mixonic** [comment]
:heart_eyes:

**Pull request merged**
