### PR TITLE
(Requires Dropping Node v0.12.x support) Migrate jshint to eslint

### PR DESCRIPTION
**Pull request by samtsai**
tests/.eslintrc.js rules borrowed from 'ember-cli'

/cc @quaertym @stefanpenner

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM (although tests look unhappy)

**Comment by samtsai** [comment]
Let me investigate the test issues

**Comment by samtsai** [comment]
Looks like the classic `SyntaxError: Use of const in strict mode`

**Comment by samtsai** [comment]
@stefanpenner Ugh. Looks like we'll have to delay this unless we drop support for Node v0.12.x in this plugin.

Tests are now failing on `eslint` dependencies:
https://ci.appveyor.com/project/quaertym/ember-cli-dependency-checker/build/43#L435

**Comment by stefanpenner** [comment]
> Looks like we'll have to delay this unless we drop support for Node v0.12.x in this plugin.

I believe we have now

**Comment by stefanpenner** [comment]
rebased -> https://github.com/quaertym/ember-cli-dependency-checker/pull/74

**Comment by stefanpenner** [comment]
merged with #74

**Pull request closed without merging**
